# using Cypress CircleCI Orb
# https://github.com/cypress-io/circleci-orb
version: 2.1
orbs:
  cypress: cypress-io/cypress@1

jobs:
  tests-passed:
    # job will always execute, but will halt if the
    # test results say "failed"
    executor: cypress/base-10
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la
      - run: cat test-results.json
      - run: |
          if ! node ./tests-passed; then
            echo "Tests failed, halting"
            circleci-agent step halt
          fi
      - run: echo "Doing whatever is needed on success"

  tests-failed:
    # job will always execute, but will halt if the
    # test results say "passed"
    executor: cypress/base-10
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la
      - run: cat test-results.json || true
      - run: |
          if node ./tests-passed; then
            echo "Tests passed, halting"
            circleci-agent step halt
          fi
      - run: echo "Doing whatever is needed on failure"

workflows:
  build:
    jobs:
      - cypress/run:
          # note: does not fail the build
          command: npm run ci
          post-steps:
            # save test results file in the workspace
            - run: cat test-results.json
            - persist_to_workspace:
                root: /
                paths:
                  - root/project/test-results.json

      - tests-passed:
          requires:
            - cypress/run
      - tests-failed:
          requires:
            - cypress/run
